# Generated by Django 5.2 on 2025-07-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_service', '0002_alter_order_options_order_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_service.service'),
            preserve_default=False,
        ),
    ]
