# Generated by Django 5.2 on 2025-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_service', '0003_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.IntegerField(),
        ),
    ]
