# Generated by Django 5.2 on 2025-07-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_service', '0004_alter_order_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='system_role',
        ),
    ]
